/** Familiar placeholder names for newly created chats. */

// Curated from USDA FoodData Central FNDDS 2021–2023 (CC0 1.0):
// https://fdc.nal.usda.gov/download-datasets/
export const foodChatNames = [
  "Pancakes",
  "Waffles",
  "French Toast",
  "Scrambled Eggs",
  "Fried Eggs",
  "Poached Eggs",
  "Boiled Eggs",
  "Egg Sandwich",
  "Breakfast Burrito",
  "Breakfast Tacos",
  "Avocado Toast",
  "Buttered Toast",
  "Cinnamon Toast",
  "Bagel and Cream Cheese",
  "English Muffin",
  "Blueberry Muffin",
  "Banana Muffin",
  "Chocolate Chip Muffin",
  "Croissant",
  "Cheese Danish",
  "Cinnamon Roll",
  "Biscuits and Gravy",
  "Sausage Biscuit",
  "Bacon and Eggs",
  "Sausage and Eggs",
  "Ham and Eggs",
  "Hash Browns",
  "Home Fries",
  "Breakfast Potatoes",
  "Oatmeal",
  "Overnight Oats",
  "Granola",
  "Yogurt Parfait",
  "Fruit Salad",
  "Breakfast Cereal",
  "Corn Flakes",
  "Granola Bar",
  "Peanut Butter Toast",
  "Jelly Toast",
  "Breakfast Sandwich",
  "Egg and Cheese Biscuit",
  "Bacon Egg and Cheese",
  "Sausage Egg and Cheese",
  "Ham Egg and Cheese",
  "Eggs Benedict",
  "Cheese Omelet",
  "Western Omelet",
  "Vegetable Omelet",
  "Breakfast Quesadilla",
  "Chocolate Croissant",
  "Banana Bread",
  "Zucchini Bread",
  "Cornbread",
  "Garlic Bread",
  "Dinner Roll",
  "Sourdough Bread",
  "Whole Wheat Bread",
  "White Bread",
  "Pita Bread",
  "Naan Bread",
  "Cheeseburger",
  "Hamburger",
  "Bacon Cheeseburger",
  "Veggie Burger",
  "Turkey Burger",
  "Chicken Sandwich",
  "Grilled Chicken Sandwich",
  "Fried Chicken Sandwich",
  "Spicy Chicken Sandwich",
  "Fish Sandwich",
  "Pulled Pork Sandwich",
  "Roast Beef Sandwich",
  "Turkey Sandwich",
  "Ham Sandwich",
  "Tuna Sandwich",
  "Egg Salad Sandwich",
  "Chicken Salad Sandwich",
  "Grilled Cheese",
  "Peanut Butter and Jelly",
  "BLT Sandwich",
  "Club Sandwich",
  "Meatball Sub",
  "Italian Sub",
  "Philly Cheesesteak",
  "French Dip",
  "Reuben Sandwich",
  "Cuban Sandwich",
  "Hot Dog",
  "Corn Dog",
  "Sloppy Joe",
  "Cheese Pizza",
  "Pepperoni Pizza",
  "Sausage Pizza",
  "Margherita Pizza",
  "Hawaiian Pizza",
  "Meat Lovers Pizza",
  "Veggie Pizza",
  "BBQ Chicken Pizza",
  "Buffalo Chicken Pizza",
  "Mushroom Pizza",
  "Spaghetti and Meatballs",
  "Spaghetti Bolognese",
  "Fettuccine Alfredo",
  "Mac and Cheese",
  "Lasagna",
  "Baked Ziti",
  "Penne Marinara",
  "Pasta Primavera",
  "Chicken Parmesan",
  "Eggplant Parmesan",
  "Stuffed Shells",
  "Cheese Ravioli",
  "Beef Ravioli",
  "Tortellini",
  "Gnocchi",
  "Pesto Pasta",
  "Pasta Salad",
  "Tuna Noodle Casserole",
  "Chicken Noodle Casserole",
  "Beef Stroganoff",
  "Chicken Alfredo",
  "Shrimp Alfredo",
  "Garlic Butter Noodles",
  "Buttered Noodles",
  "Lo Mein",
  "Chow Mein",
  "Pad Thai",
  "Drunken Noodles",
  "Sesame Noodles",
  "Ramen Noodles",
  "Chicken Noodle Soup",
  "Tomato Soup",
  "Vegetable Soup",
  "Beef Stew",
  "Chicken and Rice Soup",
  "Lentil Soup",
  "Split Pea Soup",
  "Minestrone",
  "Potato Soup",
  "Broccoli Cheddar Soup",
  "French Onion Soup",
  "Clam Chowder",
  "Corn Chowder",
  "Chili",
  "White Chicken Chili",
  "Black Bean Soup",
  "Tortilla Soup",
  "Wonton Soup",
  "Egg Drop Soup",
  "Miso Soup",
  "Gumbo",
  "Chicken Soup",
  "Mushroom Soup",
  "Butternut Squash Soup",
  "Italian Wedding Soup",
  "Caesar Salad",
  "Garden Salad",
  "Greek Salad",
  "Cobb Salad",
  "Chef Salad",
  "Chicken Caesar Salad",
  "Taco Salad",
  "Coleslaw",
  "Potato Salad",
  "Macaroni Salad",
  "Cucumber Salad",
  "Caprese Salad",
  "Spinach Salad",
  "Wedge Salad",
  "Kale Salad",
  "Three Bean Salad",
  "Ambrosia Salad",
  "Broccoli Salad",
  "Quinoa Salad",
  "Fruit and Yogurt Salad",
  "Mashed Potatoes",
  "Baked Potato",
  "Loaded Baked Potato",
  "French Fries",
  "Sweet Potato Fries",
  "Tater Tots",
  "Onion Rings",
  "Scalloped Potatoes",
  "Roasted Potatoes",
  "Sweet Potato Casserole",
  "Green Bean Casserole",
  "Baked Beans",
  "Refried Beans",
  "Black Beans and Rice",
  "Rice Pilaf",
  "Fried Rice",
  "White Rice",
  "Brown Rice",
  "Spanish Rice",
  "Cilantro Lime Rice",
  "Creamed Corn",
  "Corn on the Cob",
  "Roasted Vegetables",
  "Steamed Broccoli",
  "Glazed Carrots",
  "Fried Chicken",
  "Grilled Chicken",
  "Roast Chicken",
  "Baked Chicken",
  "BBQ Chicken",
  "Buffalo Wings",
  "Chicken Tenders",
  "Chicken Nuggets",
  "Chicken Pot Pie",
  "Chicken and Dumplings",
  "Chicken Cordon Bleu",
  "Chicken Marsala",
  "Chicken Piccata",
  "Lemon Chicken",
  "Orange Chicken",
  "Sesame Chicken",
  "General Tso Chicken",
  "Teriyaki Chicken",
  "Honey Garlic Chicken",
  "Chicken Stir Fry",
  "Chicken Fajitas",
  "Chicken Enchiladas",
  "Chicken Quesadilla",
  "Chicken Fried Rice",
  "Chicken Curry",
  "Butter Chicken",
  "Chicken Tikka Masala",
  "Chicken Shawarma",
  "Chicken Gyro",
  "Chicken Kebabs",
  "Meatloaf",
  "Pot Roast",
  "Roast Beef",
  "Beef Brisket",
  "BBQ Ribs",
  "Beef Tacos",
  "Ground Beef Tacos",
  "Steak Tacos",
  "Beef Burrito",
  "Beef Enchiladas",
  "Beef Quesadilla",
  "Beef and Broccoli",
  "Mongolian Beef",
  "Pepper Steak",
  "Beef Stir Fry",
  "Beef Fried Rice",
  "Steak and Potatoes",
  "Grilled Steak",
  "Sirloin Steak",
  "Ribeye Steak",
  "Salisbury Steak",
  "Country Fried Steak",
  "Beef Pot Pie",
  "Shepherds Pie",
  "Stuffed Peppers",
  "Stuffed Cabbage",
  "Swedish Meatballs",
  "Beef Meatballs",
  "BBQ Meatballs",
  "Beef Kebabs",
  "Pork Chops",
  "BBQ Pork Chops",
  "Roast Pork",
  "Pulled Pork",
  "Pork Tenderloin",
  "Ham Dinner",
  "Glazed Ham",
  "Bacon Wrapped Pork",
  "Sausage and Peppers",
  "Italian Sausage",
  "Breakfast Sausage",
  "Bratwurst",
  "Baby Back Ribs",
  "Pork Fried Rice",
  "Pork Dumplings",
  "Pork Egg Rolls",
  "Pork Carnitas",
  "Pork Tacos",
  "Pork Burrito",
  "Pork Schnitzel",
  "Baked Salmon",
  "Grilled Salmon",
  "Smoked Salmon",
  "Salmon Patties",
  "Fish and Chips",
  "Fried Fish",
  "Baked Cod",
  "Grilled Tilapia",
  "Tuna Casserole",
  "Tuna Salad",
  "Shrimp Cocktail",
  "Fried Shrimp",
  "Grilled Shrimp",
  "Garlic Butter Shrimp",
  "Coconut Shrimp",
  "Shrimp Scampi",
  "Shrimp Fried Rice",
  "Shrimp Tacos",
  "Crab Cakes",
  "Lobster Roll",
  "Tacos al Pastor",
  "Fish Tacos",
  "Bean Burrito",
  "Chicken Burrito",
  "California Burrito",
  "Nachos",
  "Loaded Nachos",
  "Cheese Quesadilla",
  "Cheese Enchiladas",
  "Tamales",
  "Chiles Rellenos",
  "Fajitas",
  "Taco Bowl",
  "Burrito Bowl",
  "Guacamole",
  "Salsa and Chips",
  "Huevos Rancheros",
  "Chili Con Carne",
  "Mexican Street Corn",
  "Empanadas",
  "Jamaican Jerk Chicken",
  "Rice and Beans",
  "Red Beans and Rice",
  "Jambalaya",
  "Shrimp and Grits",
  "Chicken and Waffles",
  "Biscuits and Sausage Gravy",
  "Corned Beef and Cabbage",
  "Pierogi",
  "Potato Pancakes",
  "Falafel",
  "Hummus Plate",
  "Gyro",
  "Beef Shawarma",
  "Lamb Kebabs",
  "Greek Chicken",
  "Spanakopita",
  "Moussaka",
  "Chicken Souvlaki",
  "Tzatziki and Pita",
  "Sushi Rolls",
  "California Roll",
  "Spicy Tuna Roll",
  "Salmon Roll",
  "Shrimp Tempura",
  "Teriyaki Beef",
  "Chicken Katsu",
  "Pork Katsu",
  "Beef Bulgogi",
  "Korean Fried Chicken",
  "Bibimbap",
  "Kimchi Fried Rice",
  "Dumplings",
  "Potstickers",
  "Spring Rolls",
  "Crab Rangoon",
  "Sweet and Sour Chicken",
  "Kung Pao Chicken",
  "Cashew Chicken",
  "Mapo Tofu",
  "Tofu Stir Fry",
  "Vegetable Stir Fry",
  "Vegetable Curry",
  "Chickpea Curry",
  "Thai Green Curry",
  "Thai Red Curry",
  "Coconut Curry",
  "Biryani",
  "Vegetable Samosas",
  "Garlic Naan",
  "Potato Chips",
  "Tortilla Chips",
  "Pretzels",
  "Popcorn",
  "Cheese Crackers",
  "Graham Crackers",
  "Animal Crackers",
  "Trail Mix",
  "Mixed Nuts",
  "Peanuts",
  "Almonds",
  "Cashews",
  "Pistachios",
  "Beef Jerky",
  "String Cheese",
  "Cheese and Crackers",
  "Apple Slices and Peanut Butter",
  "Celery and Peanut Butter",
  "Carrots and Ranch",
  "Chips and Guacamole",
  "Chips and Salsa",
  "Seven Layer Dip",
  "Spinach Artichoke Dip",
  "Buffalo Chicken Dip",
  "Queso Dip",
  "French Onion Dip",
  "Ranch Dip",
  "Deviled Eggs",
  "Mozzarella Sticks",
  "Jalapeno Poppers",
  "Chicken Wings",
  "Pizza Rolls",
  "Bagel Bites",
  "Soft Pretzel",
  "Nacho Cheese Fries",
  "Loaded Potato Skins",
  "Fried Pickles",
  "Hush Puppies",
  "Garlic Knots",
  "Cheese Curds",
  "Chocolate Chip Cookies",
  "Sugar Cookies",
  "Oatmeal Raisin Cookies",
  "Peanut Butter Cookies",
  "Snickerdoodles",
  "Shortbread Cookies",
  "Brownies",
  "Blondies",
  "Fudge",
  "Crispy Rice Treats",
  "Chocolate Cake",
  "Vanilla Cake",
  "Birthday Cake",
  "Carrot Cake",
  "Red Velvet Cake",
  "Cheesecake",
  "Strawberry Cheesecake",
  "Chocolate Cheesecake",
  "Pound Cake",
  "Angel Food Cake",
  "Coffee Cake",
  "Cupcakes",
  "Chocolate Cupcakes",
  "Vanilla Cupcakes",
  "Apple Pie",
  "Pumpkin Pie",
  "Pecan Pie",
  "Cherry Pie",
  "Blueberry Pie",
  "Key Lime Pie",
  "Lemon Meringue Pie",
  "Peach Cobbler",
  "Apple Crisp",
  "Bread Pudding",
  "Banana Pudding",
  "Chocolate Pudding",
  "Rice Pudding",
  "Vanilla Pudding",
  "Ice Cream Sundae",
  "Vanilla Ice Cream",
  "Chocolate Ice Cream",
  "Strawberry Ice Cream",
  "Cookies and Cream Ice Cream",
  "Mint Chocolate Chip Ice Cream",
  "Chocolate Milkshake",
  "Vanilla Milkshake",
  "Strawberry Milkshake",
  "Frozen Yogurt",
  "Ice Cream Sandwich",
  "Chocolate Donut",
  "Glazed Donut",
  "Jelly Donut",
  "Powdered Donut",
  "Apple Fritter",
  "Churros",
  "Funnel Cake",
  "Cinnamon Sugar Donuts",
  "S'mores",
  "Chocolate Covered Strawberries",
  "Banana Split",
  "Coffee",
  "Iced Coffee",
  "Latte",
  "Cappuccino",
  "Espresso",
  "Mocha",
  "Hot Chocolate",
  "Black Tea",
  "Green Tea",
  "Iced Tea",
  "Sweet Tea",
  "Lemonade",
  "Limeade",
  "Orange Juice",
  "Apple Juice",
  "Grape Juice",
  "Cranberry Juice",
  "Fruit Punch",
  "Chocolate Milk",
  "Strawberry Milk",
  "Vanilla Smoothie",
  "Strawberry Smoothie",
  "Banana Smoothie",
  "Mango Smoothie",
  "Berry Smoothie",
  "Protein Shake",
  "Root Beer Float",
  "Horchata",
  "Arnold Palmer",
  "Sparkling Water",
] as const;
